import numpy as np
from scipy.stats import multivariate_normal

class HMM:
    """
    HMM - class for Hidden Markov Models, representing
    statistical properties of random sequences.
    Each sample in the sequence is a scalar or vector, with fixed DataSize.
    
    Several HMM objects may be collected in a single multidimensional array.
    
    A HMM represents a random sequence(X1,X2,....Xt,...),
    where each element Xt can be a scalar or column vector.
    The statistical dependence along the (time) sequence is described
    entirely by a discrete Markov chain.
    
    A HMM consists of two sub-objects:
    1: a State Sequence Generator of type MarkovChain
    2: an array of output probability distributions, one for each state
    
    All states must have the same class of output distribution,
    such as GaussD, GaussMixD, or DiscreteD, etc.,
    and the set of distributions is represented by an object array of that class,
    although this is NOT required by general HMM theory.
    
    All output distributions must have identical DataSize property values.
    
    Any HMM output sequence X(t) is determined by a hidden state sequence S(t)
    generated by an internal Markov chain.
    
    The array of output probability distributions, with one element for each state,
    determines the conditional probability (density) P[X(t) | S(t)].
    Given S(t), each X(t) is independent of all other X(:).
    
    
    References:
    Leijon, A. (20xx) Pattern Recognition. KTH, Stockholm.
    Rabiner, L. R. (1989) A tutorial on hidden Markov models
    	and selected applications in speech recognition.
    	Proc IEEE 77, 257-286.
    
    """
    def __init__(self, mc, distributions):
        self.stateGen = mc
        self.outputDistr = distributions
        self.nStates = mc.nStates
        self.dataSize = distributions[0].dataSize
    def rand(self, nSamples):
        """
        [X,S]=rand(self,nSamples); generates a random sequence of data
        from a given Hidden Markov Model.
        
        Input:
        nSamples=  maximum no of output samples (scalars or column vectors)
        
        Result:
        X= matrix or row vector with output data samples
        S= row vector with corresponding integer state values
          obtained from the self.StateGen component.
          nS= length(S) == size(X,2)= number of output samples.
          If the StateGen can generate infinite-duration sequences,
              nS == nSamples
          If the StateGen is a finite-duration MarkovChain,
              nS <= nSamples
        """
        
        S = self.stateGen.rand(nSamples)
        nS = len(S)
        
        if self.dataSize == 1:
            X = np.zeros(nS)
        else:
            X = np.zeros((self.dataSize, nS))
        
        for t, state in enumerate(S):
            distr = self.outputDistr[state-1]
            
            if isinstance(distr, GaussD):
                x = distr.rand(1)
            elif isinstance(distr, DiscreteD):
                x = distr.rand(1)
            else:
                raise ValueError("Unsupported distribution type")
            
            if self.dataSize == 1:
                X[t] = x
            else:
                X[:, t] = x.reshape(-1)
        
        return X, S
    
    def forward(self, observations):
        T = len(observations)
        N = self.nStates
        alpha = np.zeros((N, T))
        c = np.zeros(T)

        for i in range(N):
            alpha[i, 0] = self.stateGen.q[i] * self.outputDistr[i].prob(observations[0])
        c[0] = 1.0 / np.sum(alpha[:, 0])
        alpha[:, 0] *= c[0]

        for t in range(1, T):
            for j in range(N):
                alpha[j, t] = self.outputDistr[j].prob(observations[t]) * np.sum(alpha[:, t-1] * self.stateGen.A[:, j])
            c[t] = 1.0 / np.sum(alpha[:, t])
            alpha[:, t] *= c[t]

        return alpha, c

    def backward(self, observations, c):
        T = len(observations)
        N = self.nStates
        beta = np.zeros((N, T))

        beta[:, T-1] = c[T-1]

        for t in range(T-2, -1, -1):
            for i in range(N):
                beta[i, t] = np.sum(
                    self.stateGen.A[i, :] * 
                    self.outputDistr.prob(observations[t+1]) * 
                    beta[:, t+1]
                )
            beta[:, t] *= c[t]

        return beta

    def train(self, observations, n_iter=10):
        for _ in range(n_iter):
            alpha, c = self.forward(observations)
            beta = self.backward(observations, c)
            T = len(observations)
            N = self.nStates

            # Compute gamma
            gamma = alpha * beta
            gamma /= gamma.sum(axis=0, keepdims=True)

            # Compute xi
            xi = np.zeros((N, N, T-1))
            for t in range(T-1):
                for i in range(N):
                    xi[i, :, t] = alpha[i, t] * self.stateGen.A[i, :] * \
                                  self.outputDistr.prob(observations[t+1]) * beta[:, t+1]
                xi[:, :, t] /= xi[:, :, t].sum()

            # Update initial probabilities
            self.stateGen.q = gamma[:, 0]

            # Update transition matrix
            trans_num = np.sum(xi, axis=2)
            trans_den = np.sum(gamma[:, :-1], axis=1, keepdims=True)
            self.stateGen.A = trans_num / np.where(trans_den == 0, 1e-10, trans_den)

            # Update emission parameters 
            for j in range(N):
                gamma_j = gamma[j, :]
                total = gamma_j.sum()
                if total == 0:
                    continue

                self.outputDistr[j].means = np.sum(observations * gamma_j[:, None], axis=0) / total

                diff = observations - self.outputDistr[j].means
                cov = np.dot((diff * gamma_j[:, None]).T, diff) / total
                self.outputDistr[j].cov = cov
                self.outputDistr[j].stdevs = np.sqrt(np.diag(cov))
                self.outputDistr[j].variance = self.outputDistr[j].stdevs ** 2

    def viterbi(self, observations):
        T = len(observations)
        N = self.nStates
        delta = np.zeros((N, T))
        psi = np.zeros((N, T), dtype=int)

        # Initialization
        delta[:, 0] = np.log(self.stateGen.q + 1e-10) + \
                     np.array([d.prob(observations[0]) for d in self.outputDistr])
        delta[:, 0] = np.where(delta[:, 0] < -1e20, -1e20, delta[:, 0])

        # Recursion
        for t in range(1, T):
            for j in range(N):
                trans_prob = np.log(self.stateGen.A[:, j] + 1e-10)
                prev = delta[:, t-1] + trans_prob
                psi[j, t] = np.argmax(prev)
                delta[j, t] = prev[psi[j, t]] + np.log(self.outputDistr[j].prob(observations[t]) + 1e-10)

        # Backtrack
        states = np.zeros(T, dtype=int)
        states[-1] = np.argmax(delta[:, -1])
        for t in range(T-2, -1, -1):
            states[t] = psi[states[t+1], t+1]

        return states + 1  # Convert to 1-based indexing

    def logprob(self, observations):
        _, c = self.forward(observations)
        return -np.sum(np.log(c))
